# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f3820fb9e9a675305aaba205bb30d88edc7f8166a4c04cb30f699eac338fe683338c883faacff6d3b4addc74ee7a7e1f509b68e7e4dcee194d2798136f86744

test:
  secret_key_base: e80e3e14c2e8d1f6e8429b5971cf954a47a4f25a64c2dd4be7b2b47c1409833aa271fc465ee1ef33c806bcf0b5f87ea1c456ef46c600769604eaf09b62293ccd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
